### ISSUE TITLE
Strange (*string Value) file in /opt

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#270]
Contains this:
```
bash-5.1# cat '<*string Value>'
tls_server_config:
  cert_file: ""
  key_file: ""
  min_version: TLS10
  max_version: TLS13
basic_auth_users: {}
```

Pretty sure this shouldn't be there.
